services:
  - type: web
    name: engine
    runtime: python
    repo: https://github.com/Semys1221/scraper
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    plan: free
    region: frankfurt
    envVars:
      - key: SUPABASE_URL
        value: https://rwaggfdqdnfyomvgnsne.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OUTSCRAPER_API_KEY
        sync: false
      - key: SMARTLEAD_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
